version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - VITE_API_URL=${VITE_API_URL}
        ports:
            - '3000:3000'
        volumes:
            - .:/usr/src/web
        command: bash -c "npm install && npm start"
        image: react
        container_name: ngcash_front
